export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', dial: '93', flag: '🇦🇫', currency: 'AFN', symbol: '؋', subunit: false },
  { code: 'AL', name: 'Albania', dial: '355', flag: '🇦🇱', currency: 'ALL', symbol: 'L', subunit: false },
  { code: 'DZ', name: 'Algeria', dial: '213', flag: '🇩🇿', currency: 'DZD', symbol: 'DA', subunit: false },
  { code: 'AO', name: 'Angola', dial: '244', flag: '🇦🇴', currency: 'AOA', symbol: 'Kz', subunit: false },
  { code: 'AR', name: 'Argentina', dial: '54', flag: '🇦🇷', currency: 'ARS', symbol: '$', subunit: false },
  { code: 'AU', name: 'Australia', dial: '61', flag: '🇦🇺', currency: 'AUD', symbol: 'A$', subunit: false },
  { code: 'AT', name: 'Austria', dial: '43', flag: '🇦🇹', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'BD', name: 'Bangladesh', dial: '880', flag: '🇧🇩', currency: 'BDT', symbol: '৳', subunit: false },
  { code: 'BE', name: 'Belgium', dial: '32', flag: '🇧🇪', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'BJ', name: 'Benin', dial: '229', flag: '🇧🇯', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'BO', name: 'Bolivia', dial: '591', flag: '🇧🇴', currency: 'BOB', symbol: 'Bs', subunit: false },
  { code: 'BR', name: 'Brazil', dial: '55', flag: '🇧🇷', currency: 'BRL', symbol: 'R$', subunit: false },
  { code: 'BF', name: 'Burkina Faso', dial: '226', flag: '🇧🇫', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'BI', name: 'Burundi', dial: '257', flag: '🇧🇮', currency: 'BIF', symbol: 'Fr', subunit: false },
  { code: 'CM', name: 'Cameroon', dial: '237', flag: '🇨🇲', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'CA', name: 'Canada', dial: '1', flag: '🇨🇦', currency: 'CAD', symbol: 'C$', subunit: false },
  { code: 'CV', name: 'Cape Verde', dial: '238', flag: '🇨🇻', currency: 'CVE', symbol: '$', subunit: false },
  { code: 'CF', name: 'Central African Republic', dial: '236', flag: '🇨🇫', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'TD', name: 'Chad', dial: '235', flag: '🇹🇩', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'CL', name: 'Chile', dial: '56', flag: '🇨🇱', currency: 'CLP', symbol: '$', subunit: false },
  { code: 'CN', name: 'China', dial: '86', flag: '🇨🇳', currency: 'CNY', symbol: '¥', subunit: false },
  { code: 'CO', name: 'Colombia', dial: '57', flag: '🇨🇴', currency: 'COP', symbol: '$', subunit: false },
  { code: 'CG', name: 'Congo', dial: '242', flag: '🇨🇬', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'CD', name: 'DR Congo', dial: '243', flag: '🇨🇩', currency: 'CDF', symbol: 'Fr', subunit: false },
  { code: 'CR', name: 'Costa Rica', dial: '506', flag: '🇨🇷', currency: 'CRC', symbol: '₡', subunit: false },
  { code: 'CI', name: "Côte d'Ivoire", dial: '225', flag: '🇨🇮', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'HR', name: 'Croatia', dial: '385', flag: '🇭🇷', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'CU', name: 'Cuba', dial: '53', flag: '🇨🇺', currency: 'CUP', symbol: '$', subunit: false },
  { code: 'CY', name: 'Cyprus', dial: '357', flag: '🇨🇾', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'CZ', name: 'Czech Republic', dial: '420', flag: '🇨🇿', currency: 'CZK', symbol: 'Kč', subunit: false },
  { code: 'DK', name: 'Denmark', dial: '45', flag: '🇩🇰', currency: 'DKK', symbol: 'kr', subunit: false },
  { code: 'DO', name: 'Dominican Republic', dial: '1809', flag: '🇩🇴', currency: 'DOP', symbol: 'RD$', subunit: false },
  { code: 'EC', name: 'Ecuador', dial: '593', flag: '🇪🇨', currency: 'USD', symbol: '$', subunit: false },
  { code: 'EG', name: 'Egypt', dial: '20', flag: '🇪🇬', currency: 'EGP', symbol: 'E£', subunit: false },
  { code: 'SV', name: 'El Salvador', dial: '503', flag: '🇸🇻', currency: 'USD', symbol: '$', subunit: false },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '240', flag: '🇬🇶', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'ER', name: 'Eritrea', dial: '291', flag: '🇪🇷', currency: 'ERN', symbol: 'Nfk', subunit: false },
  { code: 'ET', name: 'Ethiopia', dial: '251', flag: '🇪🇹', currency: 'ETB', symbol: 'Br', subunit: false },
  { code: 'FJ', name: 'Fiji', dial: '679', flag: '🇫🇯', currency: 'FJD', symbol: 'FJ$', subunit: false },
  { code: 'FI', name: 'Finland', dial: '358', flag: '🇫🇮', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'FR', name: 'France', dial: '33', flag: '🇫🇷', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'GA', name: 'Gabon', dial: '241', flag: '🇬🇦', currency: 'XAF', symbol: 'CFA', subunit: false },
  { code: 'GM', name: 'Gambia', dial: '220', flag: '🇬🇲', currency: 'GMD', symbol: 'D', subunit: false },
  { code: 'DE', name: 'Germany', dial: '49', flag: '🇩🇪', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'GH', name: 'Ghana', dial: '233', flag: '🇬🇭', currency: 'GHS', symbol: 'GH₵', subunit: false },
  { code: 'GR', name: 'Greece', dial: '30', flag: '🇬🇷', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'GT', name: 'Guatemala', dial: '502', flag: '🇬🇹', currency: 'GTQ', symbol: 'Q', subunit: false },
  { code: 'GN', name: 'Guinea', dial: '224', flag: '🇬🇳', currency: 'GNF', symbol: 'Fr', subunit: false },
  { code: 'GW', name: 'Guinea-Bissau', dial: '245', flag: '🇬🇼', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'GY', name: 'Guyana', dial: '592', flag: '🇬🇾', currency: 'GYD', symbol: '$', subunit: false },
  { code: 'HT', name: 'Haiti', dial: '509', flag: '🇭🇹', currency: 'HTG', symbol: 'G', subunit: false },
  { code: 'HN', name: 'Honduras', dial: '504', flag: '🇭🇳', currency: 'HNL', symbol: 'L', subunit: false },
  { code: 'HK', name: 'Hong Kong', dial: '852', flag: '🇭🇰', currency: 'HKD', symbol: 'HK$', subunit: false },
  { code: 'HU', name: 'Hungary', dial: '36', flag: '🇭🇺', currency: 'HUF', symbol: 'Ft', subunit: false },
  { code: 'IN', name: 'India', dial: '91', flag: '🇮🇳', currency: 'INR', symbol: '₹', subunit: false },
  { code: 'ID', name: 'Indonesia', dial: '62', flag: '🇮🇩', currency: 'IDR', symbol: 'Rp', subunit: false },
  { code: 'IR', name: 'Iran', dial: '98', flag: '🇮🇷', currency: 'IRR', symbol: '﷼', subunit: false },
  { code: 'IQ', name: 'Iraq', dial: '964', flag: '🇮🇶', currency: 'IQD', symbol: 'IQD', subunit: false },
  { code: 'IE', name: 'Ireland', dial: '353', flag: '🇮🇪', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'IL', name: 'Israel', dial: '972', flag: '🇮🇱', currency: 'ILS', symbol: '₪', subunit: false },
  { code: 'IT', name: 'Italy', dial: '39', flag: '🇮🇹', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'JM', name: 'Jamaica', dial: '1876', flag: '🇯🇲', currency: 'JMD', symbol: 'J$', subunit: false },
  { code: 'JP', name: 'Japan', dial: '81', flag: '🇯🇵', currency: 'JPY', symbol: '¥', subunit: false },
  { code: 'JO', name: 'Jordan', dial: '962', flag: '🇯🇴', currency: 'JOD', symbol: 'JD', subunit: false },
  { code: 'KZ', name: 'Kazakhstan', dial: '7', flag: '🇰🇿', currency: 'KZT', symbol: '₸', subunit: false },
  { code: 'KE', name: 'Kenya', dial: '254', flag: '🇰🇪', currency: 'KES', symbol: 'KSh', subunit: false },
  { code: 'KW', name: 'Kuwait', dial: '965', flag: '🇰🇼', currency: 'KWD', symbol: 'KD', subunit: false },
  { code: 'LB', name: 'Lebanon', dial: '961', flag: '🇱🇧', currency: 'LBP', symbol: 'L£', subunit: false },
  { code: 'LR', name: 'Liberia', dial: '231', flag: '🇱🇷', currency: 'LRD', symbol: '$', subunit: false },
  { code: 'LY', name: 'Libya', dial: '218', flag: '🇱🇾', currency: 'LYD', symbol: 'LD', subunit: false },
  { code: 'MG', name: 'Madagascar', dial: '261', flag: '🇲🇬', currency: 'MGA', symbol: 'Ar', subunit: false },
  { code: 'MW', name: 'Malawi', dial: '265', flag: '🇲🇼', currency: 'MWK', symbol: 'MK', subunit: false },
  { code: 'MY', name: 'Malaysia', dial: '60', flag: '🇲🇾', currency: 'MYR', symbol: 'RM', subunit: false },
  { code: 'ML', name: 'Mali', dial: '223', flag: '🇲🇱', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'MR', name: 'Mauritania', dial: '222', flag: '🇲🇷', currency: 'MRU', symbol: 'UM', subunit: false },
  { code: 'MU', name: 'Mauritius', dial: '230', flag: '🇲🇺', currency: 'MUR', symbol: '₨', subunit: false },
  { code: 'MX', name: 'Mexico', dial: '52', flag: '🇲🇽', currency: 'MXN', symbol: '$', subunit: false },
  { code: 'MD', name: 'Moldova', dial: '373', flag: '🇲🇩', currency: 'MDL', symbol: 'L', subunit: false },
  { code: 'MA', name: 'Morocco', dial: '212', flag: '🇲🇦', currency: 'MAD', symbol: 'MAD', subunit: false },
  { code: 'MZ', name: 'Mozambique', dial: '258', flag: '🇲🇿', currency: 'MZN', symbol: 'MT', subunit: false },
  { code: 'MM', name: 'Myanmar', dial: '95', flag: '🇲🇲', currency: 'MMK', symbol: 'K', subunit: false },
  { code: 'NA', name: 'Namibia', dial: '264', flag: '🇳🇦', currency: 'NAD', symbol: 'N$', subunit: false },
  { code: 'NL', name: 'Netherlands', dial: '31', flag: '🇳🇱', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'NZ', name: 'New Zealand', dial: '64', flag: '🇳🇿', currency: 'NZD', symbol: 'NZ$', subunit: false },
  { code: 'NI', name: 'Nicaragua', dial: '505', flag: '🇳🇮', currency: 'NIO', symbol: 'C$', subunit: false },
  { code: 'NE', name: 'Niger', dial: '227', flag: '🇳🇪', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'NG', name: 'Nigeria', dial: '234', flag: '🇳🇬', currency: 'NGN', symbol: '₦', subunit: true },
  { code: 'NO', name: 'Norway', dial: '47', flag: '🇳🇴', currency: 'NOK', symbol: 'kr', subunit: false },
  { code: 'OM', name: 'Oman', dial: '968', flag: '🇴🇲', currency: 'OMR', symbol: 'OMR', subunit: false },
  { code: 'PK', name: 'Pakistan', dial: '92', flag: '🇵🇰', currency: 'PKR', symbol: '₨', subunit: false },
  { code: 'PA', name: 'Panama', dial: '507', flag: '🇵🇦', currency: 'USD', symbol: '$', subunit: false },
  { code: 'PG', name: 'Papua New Guinea', dial: '675', flag: '🇵🇬', currency: 'PGK', symbol: 'K', subunit: false },
  { code: 'PY', name: 'Paraguay', dial: '595', flag: '🇵🇾', currency: 'PYG', symbol: '₲', subunit: false },
  { code: 'PE', name: 'Peru', dial: '51', flag: '🇵🇪', currency: 'PEN', symbol: 'S/', subunit: false },
  { code: 'PH', name: 'Philippines', dial: '63', flag: '🇵🇭', currency: 'PHP', symbol: '₱', subunit: false },
  { code: 'PL', name: 'Poland', dial: '48', flag: '🇵🇱', currency: 'PLN', symbol: 'zł', subunit: false },
  { code: 'PT', name: 'Portugal', dial: '351', flag: '🇵🇹', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'QA', name: 'Qatar', dial: '974', flag: '🇶🇦', currency: 'QAR', symbol: 'QR', subunit: false },
  { code: 'RO', name: 'Romania', dial: '40', flag: '🇷🇴', currency: 'RON', symbol: 'lei', subunit: false },
  { code: 'RU', name: 'Russia', dial: '7', flag: '🇷🇺', currency: 'RUB', symbol: '₽', subunit: false },
  { code: 'RW', name: 'Rwanda', dial: '250', flag: '🇷🇼', currency: 'RWF', symbol: 'Fr', subunit: false },
  { code: 'SA', name: 'Saudi Arabia', dial: '966', flag: '🇸🇦', currency: 'SAR', symbol: 'SR', subunit: false },
  { code: 'SN', name: 'Senegal', dial: '221', flag: '🇸🇳', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'SL', name: 'Sierra Leone', dial: '232', flag: '🇸🇱', currency: 'SLL', symbol: 'Le', subunit: false },
  { code: 'SG', name: 'Singapore', dial: '65', flag: '🇸🇬', currency: 'SGD', symbol: 'S$', subunit: false },
  { code: 'SO', name: 'Somalia', dial: '252', flag: '🇸🇴', currency: 'SOS', symbol: 'Sh', subunit: false },
  { code: 'ZA', name: 'South Africa', dial: '27', flag: '🇿🇦', currency: 'ZAR', symbol: 'R', subunit: false },
  { code: 'KR', name: 'South Korea', dial: '82', flag: '🇰🇷', currency: 'KRW', symbol: '₩', subunit: false },
  { code: 'SS', name: 'South Sudan', dial: '211', flag: '🇸🇸', currency: 'SSP', symbol: '£', subunit: false },
  { code: 'ES', name: 'Spain', dial: '34', flag: '🇪🇸', currency: 'EUR', symbol: '€', subunit: false },
  { code: 'LK', name: 'Sri Lanka', dial: '94', flag: '🇱🇰', currency: 'LKR', symbol: '₨', subunit: false },
  { code: 'SD', name: 'Sudan', dial: '249', flag: '🇸🇩', currency: 'SDG', symbol: 'SDG', subunit: false },
  { code: 'SR', name: 'Suriname', dial: '597', flag: '🇸🇷', currency: 'SRD', symbol: '$', subunit: false },
  { code: 'SE', name: 'Sweden', dial: '46', flag: '🇸🇪', currency: 'SEK', symbol: 'kr', subunit: false },
  { code: 'CH', name: 'Switzerland', dial: '41', flag: '🇨🇭', currency: 'CHF', symbol: 'Fr', subunit: false },
  { code: 'SY', name: 'Syria', dial: '963', flag: '🇸🇾', currency: 'SYP', symbol: '£', subunit: false },
  { code: 'TW', name: 'Taiwan', dial: '886', flag: '🇹🇼', currency: 'TWD', symbol: 'NT$', subunit: false },
  { code: 'TZ', name: 'Tanzania', dial: '255', flag: '🇹🇿', currency: 'TZS', symbol: 'Sh', subunit: false },
  { code: 'TH', name: 'Thailand', dial: '66', flag: '🇹🇭', currency: 'THB', symbol: '฿', subunit: false },
  { code: 'TG', name: 'Togo', dial: '228', flag: '🇹🇬', currency: 'XOF', symbol: 'CFA', subunit: false },
  { code: 'TT', name: 'Trinidad and Tobago', dial: '1868', flag: '🇹🇹', currency: 'TTD', symbol: 'TT$', subunit: false },
  { code: 'TN', name: 'Tunisia', dial: '216', flag: '🇹🇳', currency: 'TND', symbol: 'DT', subunit: false },
  { code: 'TR', name: 'Turkey', dial: '90', flag: '🇹🇷', currency: 'TRY', symbol: '₺', subunit: false },
  { code: 'UG', name: 'Uganda', dial: '256', flag: '🇺🇬', currency: 'UGX', symbol: 'Sh', subunit: false },
  { code: 'UA', name: 'Ukraine', dial: '380', flag: '🇺🇦', currency: 'UAH', symbol: '₴', subunit: false },
  { code: 'AE', name: 'United Arab Emirates', dial: '971', flag: '🇦🇪', currency: 'AED', symbol: 'AED', subunit: false },
  { code: 'GB', name: 'United Kingdom', dial: '44', flag: '🇬🇧', currency: 'GBP', symbol: '£', subunit: false },
  { code: 'US', name: 'United States', dial: '1', flag: '🇺🇸', currency: 'USD', symbol: '$', subunit: false },
  { code: 'UY', name: 'Uruguay', dial: '598', flag: '🇺🇾', currency: 'UYU', symbol: '$U', subunit: false },
  { code: 'UZ', name: 'Uzbekistan', dial: '998', flag: '🇺🇿', currency: 'UZS', symbol: 'soʻm', subunit: false },
  { code: 'VE', name: 'Venezuela', dial: '58', flag: '🇻🇪', currency: 'VES', symbol: 'Bs.', subunit: false },
  { code: 'VN', name: 'Vietnam', dial: '84', flag: '🇻🇳', currency: 'VND', symbol: '₫', subunit: false },
  { code: 'YE', name: 'Yemen', dial: '967', flag: '🇾🇪', currency: 'YER', symbol: '﷼', subunit: false },
  { code: 'ZM', name: 'Zambia', dial: '260', flag: '🇿🇲', currency: 'ZMW', symbol: 'ZK', subunit: false },
  { code: 'ZW', name: 'Zimbabwe', dial: '263', flag: '🇿🇼', currency: 'ZWL', symbol: '$', subunit: false },
  { code: 'OTHER', name: 'Other', dial: '', flag: '🌍', currency: 'USD', symbol: '$', subunit: false },
]

// Returns { symbol, subunit } for a given country code
// subunit: true means prices are stored in smallest unit (e.g. kobo for Nigeria) — divide by 100 to display
// subunit: false means prices are stored as whole units (e.g. GH₵ for Ghana) — display as-is
export function getCurrency(countryCode: string | undefined | null): { symbol: string; subunit: boolean } {
  const country = COUNTRIES.find(c => c.code === (countryCode || 'NG'))
  return { symbol: country?.symbol ?? '₦', subunit: country?.subunit ?? true }
}

export function formatMoney(amount: number, countryCode: string | undefined | null): string {
  const { symbol, subunit } = getCurrency(countryCode)
  const value = subunit ? amount / 100 : amount
  return `${symbol}${value.toLocaleString()}`
}

export function normalizeNumber(number: string, dialCode: string) {
  const digits = number.replace(/\D/g, '')
  if (!dialCode) return digits
  const local = digits.startsWith('0') ? digits.slice(1) : digits
  return dialCode + local
}
