export const COUNTRY_LIST: Array<{ name: string; code: string; dial: string; cities: string[] }> = [
  { name: 'Nigeria', code: 'NG', dial: '234', cities: [
    'Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Ibadan', 'Benin City', 'Onitsha', 'Aba',
    'Enugu', 'Warri', 'Kaduna', 'Calabar', 'Jos', 'Ilorin', 'Abeokuta', 'Akure', 'Owerri',
    'Uyo', 'Maiduguri', 'Sokoto', 'Asaba', 'Awka', 'Bauchi', 'Birnin Kebbi', 'Damaturu',
    'Dutse', 'Gombe', 'Gusau', 'Jalingo', 'Lafia', 'Lokoja', 'Makurdi', 'Minna', 'Nnewi',
    'Ogbomosho', 'Okene', 'Ondo', 'Osogbo', 'Owerri', 'Sapele', 'Suleja', 'Umuahia',
    'Yenagoa', 'Yola', 'Zaria', 'Agbor', 'Auchi', 'Effon-Alaiye', 'Eket', 'Elele',
    'Gboko', 'Hadejia', 'Ijebu-Ode', 'Ikeja', 'Ikot Ekpene', 'Ilesa', 'Jimeta',
    'Kafanchan', 'Katsina', 'Kumo', 'Lafia', 'Lekki', 'Mushin', 'Nsukka',
    'Ogun', 'Ojo', 'Okitipupa', 'Onitsha', 'Oshogbo', 'Otukpo', 'Owerri',
    'Surulere', 'Victoria Island', 'Wukari'
  ] },
  { name: 'United States', code: 'US', dial: '1', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Nashville', 'Oklahoma City', 'El Paso', 'Las Vegas', 'Louisville', 'Memphis', 'Boston', 'Portland', 'Baltimore', 'Atlanta', 'Miami', 'Minneapolis', 'Tucson', 'Fresno', 'Sacramento', 'Mesa', 'Kansas City', 'Cleveland', 'Omaha', 'Raleigh', 'Colorado Springs', 'Virginia Beach', 'Long Beach', 'Tampa', 'New Orleans', 'Honolulu', 'Bentonville', 'Rogers', 'Fayetteville', 'Springdale'] },
  { name: 'United Kingdom', code: 'GB', dial: '44', cities: ['London', 'Birmingham', 'Manchester', 'Leeds', 'Glasgow', 'Sheffield', 'Bradford', 'Liverpool', 'Edinburgh', 'Bristol', 'Cardiff', 'Leicester', 'Coventry', 'Nottingham', 'Newcastle', 'Belfast', 'Brighton', 'Hull', 'Plymouth', 'Southampton', 'Reading', 'Derby', 'Wolverhampton', 'Stoke-on-Trent', 'Oxford', 'Cambridge'] },
  { name: 'Canada', code: 'CA', dial: '1', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'St. Catharines', 'Barrie', 'Kelowna'] },
  { name: 'Ghana', code: 'GH', dial: '233', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast', 'Sunyani', 'Koforidua', 'Ho', 'Wa', 'Bolgatanga', 'Tema', 'Obuasi', 'Techiman', 'Nkoranza', 'Kintampo', 'Berekum', 'Mampong', 'Konongo', 'Agogo', 'Sefwi Wiawso', 'Tarkwa', 'Prestea', 'Dunkwa', 'Saltpond', 'Winneba', 'Swedru', 'Nsawam', 'Akim Oda', 'Nkawkaw', 'Hohoe'] },
  { name: 'Kenya', code: 'KE', dial: '254', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Nyeri', 'Machakos', 'Naivasha', 'Kericho', 'Embu', 'Meru', 'Garissa', 'Kakamega', 'Bungoma', 'Kisii', 'Kilifi', 'Lamu', 'Muranga', 'Nanyuki', 'Athi River', 'Ruiru', 'Kikuyu', 'Isiolo', 'Voi', 'Wajir', 'Mandera', 'Marsabit'] },
  { name: 'South Africa', code: 'ZA', dial: '27', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Nelspruit', 'Kimberley', 'Polokwane', 'Rustenburg', 'George', 'Pietermaritzburg', 'Vanderbijlpark', 'Vereeniging', 'Soweto', 'Sandton', 'Centurion', 'Midrand', 'Randburg', 'Roodepoort', 'Benoni', 'Boksburg', 'Germiston', 'Springs', 'Tembisa', 'Khayelitsha', 'Mitchells Plain', 'Stellenbosch', 'Paarl', 'Worcester', 'Knysna', 'Mossel Bay', 'Richards Bay', 'Newcastle', 'Witbank', 'Klerksdorp', 'Potchefstroom', 'Upington'] },
  { name: 'Tanzania', code: 'TZ', dial: '255', cities: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Zanzibar', 'Tanga', 'Kahama', 'Tabora'] },
  { name: 'Uganda', code: 'UG', dial: '256', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono', 'Kasese', 'Masaka'] },
  { name: 'Ethiopia', code: 'ET', dial: '251', cities: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Awasa', 'Adama', 'Bahir Dar', 'Jimma', 'Dessie', 'Harar'] },
  { name: 'Egypt', code: 'EG', dial: '20', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Asyut', 'Tanta', 'Mansoura'] },
  { name: 'Senegal', code: 'SN', dial: '221', cities: ['Dakar', 'Thiès', 'Kaolack', 'Ziguinchor', 'Saint-Louis', 'Rufisque', 'Diourbel', 'Louga', 'Mbour', 'Touba'] },
  { name: 'Cameroon', code: 'CM', dial: '237', cities: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua', 'Maroua', 'Ngaoundéré', 'Bertoua', 'Kumba', 'Edéa'] },
  { name: "Côte d'Ivoire", code: 'CI', dial: '225', cities: ['Abidjan', 'Bouaké', 'Daloa', 'San-Pédro', 'Yamoussoukro', 'Korhogo', 'Gagnoa', 'Man', 'Divo', 'Abengourou'] },
  { name: 'India', code: 'IN', dial: '91', cities: ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubli', 'Mysore', 'Tiruchirappalli', 'Bareilly', 'Aligarh', 'Moradabad'] },
  { name: 'Pakistan', code: 'PK', dial: '92', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta'] },
  { name: 'Bangladesh', code: 'BD', dial: '880', cities: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Barisal', 'Comilla', 'Narayanganj', 'Gazipur', 'Mymensingh'] },
  { name: 'Malaysia', code: 'MY', dial: '60', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Kota Kinabalu', 'Kuching', 'Malacca', 'Subang Jaya'] },
  { name: 'Philippines', code: 'PH', dial: '63', cities: ['Manila', 'Quezon City', 'Caloocan', 'Davao', 'Cebu', 'Zamboanga', 'Antipolo', 'Pasig', 'Taguig', 'Valenzuela'] },
  { name: 'Indonesia', code: 'ID', dial: '62', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Depok', 'Tangerang', 'Bekasi'] },
  { name: 'Brazil', code: 'BR', dial: '55', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Goiânia'] },
  { name: 'Mexico', code: 'MX', dial: '52', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan', 'Mérida', 'San Luis Potosí'] },
  { name: 'Australia', code: 'AU', dial: '61', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Logan City'] },
  { name: 'Germany', code: 'DE', dial: '49', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'] },
  { name: 'France', code: 'FR', dial: '33', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
  { name: 'Netherlands', code: 'NL', dial: '31', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'] },
  { name: 'Italy', code: 'IT', dial: '39', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'] },
  { name: 'Spain', code: 'ES', dial: '34', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'] },
  { name: 'Portugal', code: 'PT', dial: '351', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Setúbal', 'Almada', 'Amadora', 'Vila Nova de Gaia', 'Evora'] },
  { name: 'United Arab Emirates', code: 'AE', dial: '971', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'] },
  { name: 'Saudi Arabia', code: 'SA', dial: '966', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Abha', 'Buraidah', 'Khamis Mushait'] },
  { name: 'Jamaica', code: 'JM', dial: '1876', cities: ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'May Pen', 'Mandeville', 'Old Harbour', 'Half Way Tree', 'Linstead', 'Ocho Rios'] },
  { name: 'Trinidad and Tobago', code: 'TT', dial: '1868', cities: ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Point Fortin', 'Scarborough'] },
  { name: 'Zimbabwe', code: 'ZW', dial: '263', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chinhoyi', 'Norton'] },
  { name: 'Zambia', code: 'ZM', dial: '260', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Livingstone', 'Luanshya', 'Kasama', 'Chipata'] },
  { name: 'Rwanda', code: 'RW', dial: '250', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kabgayi', 'Kibungo', 'Rwamagana'] },
  { name: 'DR Congo', code: 'CD', dial: '243', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Tshikapa', 'Kolwezi', 'Likasi', 'Goma'] },
  { name: 'Mozambique', code: 'MZ', dial: '258', cities: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala', 'Quelimane', 'Tete', 'Lichinga', 'Pemba'] },
  { name: 'Angola', code: 'AO', dial: '244', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Lubango', 'Malanje', 'Namibe', 'Soyo', 'Cabinda'] },
  { name: 'China', code: 'CN', dial: '86', cities: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Tianjin', 'Chongqing', 'Wuhan', "Xi'an", 'Hangzhou'] },
  { name: 'Japan', code: 'JP', dial: '81', cities: ['Tokyo', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Saitama', 'Hiroshima'] },
  { name: 'South Korea', code: 'KR', dial: '82', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam'] },
  { name: 'Singapore', code: 'SG', dial: '65', cities: ['Singapore'] },
  { name: 'New Zealand', code: 'NZ', dial: '64', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua', 'New Plymouth'] },
  { name: 'Ireland', code: 'IE', dial: '353', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'] },
  { name: 'Sweden', code: 'SE', dial: '46', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping'] },
  { name: 'Norway', code: 'NO', dial: '47', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'] },
  { name: 'Denmark', code: 'DK', dial: '45', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle'] },
]
