export const COUNTRY_LIST: Array<{ name: string; code: string; dial: string; cities: string[] }> = [
  { name: 'Nigeria', code: 'NG', dial: '234', cities: [
    'Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Ibadan', 'Benin City', 'Onitsha', 'Aba',
    'Enugu', 'Warri', 'Kaduna', 'Calabar', 'Jos', 'Ilorin', 'Abeokuta', 'Akure', 'Owerri',
    'Uyo', 'Maiduguri', 'Sokoto', 'Asaba', 'Awka', 'Bauchi', 'Birnin Kebbi', 'Damaturu',
    'Dutse', 'Gombe', 'Gusau', 'Jalingo', 'Lafia', 'Lokoja', 'Makurdi', 'Minna', 'Nnewi',
    'Ogbomosho', 'Okene', 'Ondo', 'Osogbo', 'Owerri', 'Sapele', 'Suleja', 'Umuahia',
    'Yenagoa', 'Yola', 'Zaria', 'Agbor', 'Auchi', 'Effon-Alaiye', 'Eket', 'Elele',
    'Gboko', 'Hadejia', 'Ijebu-Ode', 'Ikeja', 'Ikot Ekpene', 'Ilesa', 'Jimeta',
    'Kafanchan', 'Katsina', 'Kumo', 'Lafia', 'Lekki', 'Mushin', 'Nsukka',
    'Ogun', 'Ojo', 'Okitipupa', 'Onitsha', 'Oshogbo', 'Otukpo', 'Owerri',
    'Surulere', 'Victoria Island', 'Wukari'
  ] },
  { name: 'United States', code: 'US', dial: '1', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle', 'Denver', 'Nashville', 'Oklahoma City', 'El Paso', 'Las Vegas', 'Louisville', 'Memphis', 'Boston', 'Portland', 'Baltimore', 'Atlanta', 'Miami', 'Minneapolis', 'Tucson', 'Fresno', 'Sacramento', 'Mesa', 'Kansas City', 'Cleveland', 'Omaha', 'Raleigh', 'Colorado Springs', 'Virginia Beach', 'Long Beach', 'Tampa', 'New Orleans', 'Honolulu', 'Bentonville', 'Rogers', 'Fayetteville', 'Springdale'] },
  { name: 'United Kingdom', code: 'GB', dial: '44', cities: ['London', 'Birmingham', 'Manchester', 'Leeds', 'Glasgow', 'Sheffield', 'Bradford', 'Liverpool', 'Edinburgh', 'Bristol', 'Cardiff', 'Leicester', 'Coventry', 'Nottingham', 'Newcastle', 'Belfast', 'Brighton', 'Hull', 'Plymouth', 'Southampton', 'Reading', 'Derby', 'Wolverhampton', 'Stoke-on-Trent', 'Oxford', 'Cambridge'] },
  { name: 'Canada', code: 'CA', dial: '1', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'St. Catharines', 'Barrie', 'Kelowna'] },
  { name: 'Ghana', code: 'GH', dial: '233', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast', 'Sunyani', 'Koforidua', 'Ho', 'Wa', 'Bolgatanga', 'Tema', 'Obuasi', 'Techiman', 'Nkoranza', 'Kintampo', 'Berekum', 'Mampong', 'Konongo', 'Agogo', 'Sefwi Wiawso', 'Tarkwa', 'Prestea', 'Dunkwa', 'Saltpond', 'Winneba', 'Swedru', 'Nsawam', 'Akim Oda', 'Nkawkaw', 'Hohoe'] },
  { name: 'Kenya', code: 'KE', dial: '254', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Nyeri', 'Machakos', 'Naivasha', 'Kericho', 'Embu', 'Meru', 'Garissa', 'Kakamega', 'Bungoma', 'Kisii', 'Kilifi', 'Lamu', 'Muranga', 'Nanyuki', 'Athi River', 'Ruiru', 'Kikuyu', 'Isiolo', 'Voi', 'Wajir', 'Mandera', 'Marsabit'] },
  { name: 'South Africa', code: 'ZA', dial: '27', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Nelspruit', 'Kimberley', 'Polokwane', 'Rustenburg', 'George', 'Pietermaritzburg', 'Vanderbijlpark', 'Vereeniging', 'Soweto', 'Sandton', 'Centurion', 'Midrand', 'Randburg', 'Roodepoort', 'Benoni', 'Boksburg', 'Germiston', 'Springs', 'Tembisa', 'Khayelitsha', 'Mitchells Plain', 'Stellenbosch', 'Paarl', 'Worcester', 'Knysna', 'Mossel Bay', 'Richards Bay', 'Newcastle', 'Witbank', 'Klerksdorp', 'Potchefstroom', 'Upington'] },
  { name: 'Tanzania', code: 'TZ', dial: '255', cities: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Zanzibar', 'Tanga', 'Kahama', 'Tabora'] },
  { name: 'Uganda', code: 'UG', dial: '256', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono', 'Kasese', 'Masaka'] },
  { name: 'Ethiopia', code: 'ET', dial: '251', cities: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Awasa', 'Adama', 'Bahir Dar', 'Jimma', 'Dessie', 'Harar'] },
  { name: 'Egypt', code: 'EG', dial: '20', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Asyut', 'Tanta', 'Mansoura'] },
  { name: 'Senegal', code: 'SN', dial: '221', cities: ['Dakar', 'Thiès', 'Kaolack', 'Ziguinchor', 'Saint-Louis', 'Rufisque', 'Diourbel', 'Louga', 'Mbour', 'Touba'] },
  { name: 'Cameroon', code: 'CM', dial: '237', cities: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua', 'Maroua', 'Ngaoundéré', 'Bertoua', 'Kumba', 'Edéa'] },
  { name: "Côte d'Ivoire", code: 'CI', dial: '225', cities: ['Abidjan', 'Bouaké', 'Daloa', 'San-Pédro', 'Yamoussoukro', 'Korhogo', 'Gagnoa', 'Man', 'Divo', 'Abengourou'] },
  { name: 'India', code: 'IN', dial: '91', cities: ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Guwahati', 'Chandigarh', 'Solapur', 'Hubli', 'Mysore', 'Tiruchirappalli', 'Bareilly', 'Aligarh', 'Moradabad'] },
  { name: 'Pakistan', code: 'PK', dial: '92', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta'] },
  { name: 'Bangladesh', code: 'BD', dial: '880', cities: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Barisal', 'Comilla', 'Narayanganj', 'Gazipur', 'Mymensingh'] },
  { name: 'Malaysia', code: 'MY', dial: '60', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Kota Kinabalu', 'Kuching', 'Malacca', 'Subang Jaya'] },
  { name: 'Philippines', code: 'PH', dial: '63', cities: ['Manila', 'Quezon City', 'Caloocan', 'Davao', 'Cebu', 'Zamboanga', 'Antipolo', 'Pasig', 'Taguig', 'Valenzuela'] },
  { name: 'Indonesia', code: 'ID', dial: '62', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Depok', 'Tangerang', 'Bekasi'] },
  { name: 'Brazil', code: 'BR', dial: '55', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Goiânia'] },
  { name: 'Mexico', code: 'MX', dial: '52', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan', 'Mérida', 'San Luis Potosí'] },
  { name: 'Australia', code: 'AU', dial: '61', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Logan City'] },
  { name: 'Germany', code: 'DE', dial: '49', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'] },
  { name: 'France', code: 'FR', dial: '33', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
  { name: 'Netherlands', code: 'NL', dial: '31', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'] },
  { name: 'Italy', code: 'IT', dial: '39', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'] },
  { name: 'Spain', code: 'ES', dial: '34', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'] },
  { name: 'Portugal', code: 'PT', dial: '351', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Setúbal', 'Almada', 'Amadora', 'Vila Nova de Gaia', 'Evora'] },
  { name: 'United Arab Emirates', code: 'AE', dial: '971', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'] },
  { name: 'Saudi Arabia', code: 'SA', dial: '966', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Abha', 'Buraidah', 'Khamis Mushait'] },
  { name: 'Jamaica', code: 'JM', dial: '1876', cities: ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'May Pen', 'Mandeville', 'Old Harbour', 'Half Way Tree', 'Linstead', 'Ocho Rios'] },
  { name: 'Trinidad and Tobago', code: 'TT', dial: '1868', cities: ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima', 'Point Fortin', 'Scarborough'] },
  { name: 'Zimbabwe', code: 'ZW', dial: '263', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chinhoyi', 'Norton'] },
  { name: 'Zambia', code: 'ZM', dial: '260', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Livingstone', 'Luanshya', 'Kasama', 'Chipata'] },
  { name: 'Rwanda', code: 'RW', dial: '250', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kabgayi', 'Kibungo', 'Rwamagana'] },
  { name: 'DR Congo', code: 'CD', dial: '243', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Tshikapa', 'Kolwezi', 'Likasi', 'Goma'] },
  { name: 'Mozambique', code: 'MZ', dial: '258', cities: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala', 'Quelimane', 'Tete', 'Lichinga', 'Pemba'] },
  { name: 'Angola', code: 'AO', dial: '244', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito', 'Lubango', 'Malanje', 'Namibe', 'Soyo', 'Cabinda'] },
  { name: 'China', code: 'CN', dial: '86', cities: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Tianjin', 'Chongqing', 'Wuhan', 'Xian', 'Hangzhou'] },
  { name: 'Japan', code: 'JP', dial: '81', cities: ['Tokyo', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Saitama', 'Hiroshima'] },
  { name: 'South Korea', code: 'KR', dial: '82', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam'] },
  { name: 'Singapore', code: 'SG', dial: '65', cities: ['Singapore'] },
  { name: 'New Zealand', code: 'NZ', dial: '64', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua', 'New Plymouth'] },
  { name: 'Ireland', code: 'IE', dial: '353', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'] },
  { name: 'Sweden', code: 'SE', dial: '46', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping'] },
  { name: 'Norway', code: 'NO', dial: '47', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'] },
  { name: 'Denmark', code: 'DK', dial: '45', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle'] },

  { name: 'Algeria', code: 'DZ', dial: '213', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Djelfa', 'Sétif', 'Sidi Bel Abbès', 'Biskra', 'Tébessa', 'El Oued', 'Skikda', 'Tiaret', 'Béjaïa', 'Tlemcen', 'Ouargla', 'Mostaganem', 'Bordj Bou Arréridj', 'Médéa'] },
  { name: 'Afghanistan', code: 'AF', dial: '93', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Kunduz', 'Jalalabad', 'Ghazni', 'Balkh', 'Baghlan', 'Khost'] },
  { name: 'Albania', code: 'AL', dial: '355', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier', 'Korçë', 'Elbasan', 'Berat', 'Lushnjë', 'Gjirokastër'] },
  { name: 'Argentina', code: 'AR', dial: '54', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan', 'Resistencia', 'Neuquén', 'Corrientes', 'Posadas', 'Santiago del Estero', 'Bahía Blanca', 'San Salvador de Jujuy', 'Paraná', 'Formosa', 'Río Cuarto'] },
  { name: 'Austria', code: 'AT', dial: '43', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'] },
  { name: 'Belgium', code: 'BE', dial: '32', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'] },
  { name: 'Benin', code: 'BJ', dial: '229', cities: ['Cotonou', 'Abomey-Calavi', 'Porto-Novo', 'Parakou', 'Bohicon', 'Kandi', 'Lokossa', 'Ouidah', 'Malanville', 'Natitingou'] },
  { name: 'Bolivia', code: 'BO', dial: '591', cities: ['Santa Cruz', 'La Paz', 'El Alto', 'Cochabamba', 'Oruro', 'Sucre', 'Potosí', 'Tarija', 'Montero', 'Beni'] },
  { name: 'Burkina Faso', code: 'BF', dial: '226', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya', 'Pouytenga', 'Kaya', 'Tenkodogo', 'Fada Ngourma', 'Dori'] },
  { name: 'Burundi', code: 'BI', dial: '257', cities: ['Bujumbura', 'Gitega', 'Muyinga', 'Ruyigi', 'Ngozi', 'Rumonge', 'Makamba', 'Bururi', 'Kayanza', 'Kirundo'] },
  { name: 'Cape Verde', code: 'CV', dial: '238', cities: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'São Filipe', 'Pedra Badejo', 'Tarrafal', 'Porto Novo', 'Ribeira Grande', 'Sal Rei'] },
  { name: 'Central African Republic', code: 'CF', dial: '236', cities: ['Bangui', 'Bimbo', 'Mbaïki', 'Berbérati', 'Carnot', 'Bambari', 'Bossangoa', 'Bria', 'Bouar', 'Nola'] },
  { name: 'Chad', code: 'TD', dial: '235', cities: ['Ndjamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo', 'Koumra', 'Pala', 'Am Timan', 'Bongor', 'Mongo'] },
  { name: 'Chile', code: 'CL', dial: '56', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Chillán', 'Iquique', 'Puerto Montt', 'Calama', 'Osorno', 'Valdivia', 'Copiapó', 'Quilpué', 'Viña del Mar', 'Curicó', 'Punta Arenas'] },
  { name: 'Colombia', code: 'CO', dial: '57', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué', 'Manizales', 'Bello', 'Pasto', 'Villavicencio', 'Montería', 'Palmira', 'Armenia', 'Neiva', 'Popayán', 'Floridablanca'] },
  { name: 'Congo', code: 'CG', dial: '242', cities: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Impfondo', 'Ouesso', 'Owando', 'Mossaka', 'Madingou', 'Sibiti'] },
  { name: 'Costa Rica', code: 'CR', dial: '506', cities: ['San José', 'Cartago', 'Alajuela', 'Heredia', 'Liberia', 'Puntarenas', 'Limón', 'Desamparados', 'San Carlos', 'Pérez Zeledón'] },
  { name: 'Croatia', code: 'HR', dial: '385', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula', 'Sesvete', 'Karlovac', 'Varaždin'] },
  { name: 'Cuba', code: 'CU', dial: '53', cities: ['Havana', 'Santiago de Cuba', 'Holguín', 'Camagüey', 'Santa Clara', 'Guantánamo', 'Bayamo', 'Las Tunas', 'Cienfuegos', 'Pinar del Río'] },
  { name: 'Cyprus', code: 'CY', dial: '357', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos', 'Kyrenia', 'Paralimni', 'Strovolos', 'Aglantzia', 'Latsia'] },
  { name: 'Czech Republic', code: 'CZ', dial: '420', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'Ústí nad Labem', 'České Budějovice', 'Hradec Králové', 'Pardubice'] },
  { name: 'Dominican Republic', code: 'DO', dial: '1809', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'San Cristóbal', 'Puerto Plata', 'La Vega', 'Moca', 'Barahona', 'San Francisco de Macorís'] },
  { name: 'Ecuador', code: 'EC', dial: '593', cities: ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala', 'Durán', 'Manta', 'Portoviejo', 'Loja', 'Ambato', 'Esmeraldas', 'Quevedo', 'Riobamba', 'Milagro', 'Ibarra', 'La Libertad', 'Babahoyo', 'Tulcán', 'Latacunga', 'Orellana'] },
  { name: 'El Salvador', code: 'SV', dial: '503', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango', 'Mejicanos', 'Apopa', 'Delgado', 'Usulután', 'Ahuachapán', 'Zacatecoluca'] },
  { name: 'Equatorial Guinea', code: 'GQ', dial: '240', cities: ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe', 'Añisoc', 'Luba', 'Evinayong', 'Mongomo', 'Micomeseng', 'Riaba'] },
  { name: 'Eritrea', code: 'ER', dial: '291', cities: ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera', 'Dekemhare', 'Adi Keyh', 'Barentu', 'Akurdet', 'Teseney'] },
  { name: 'Fiji', code: 'FJ', dial: '679', cities: ['Suva', 'Lautoka', 'Nadi', 'Labasa', 'Levuka', 'Ba', 'Rakiraki', 'Sigatoka', 'Tavua', 'Navua'] },
  { name: 'Finland', code: 'FI', dial: '358', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'] },
  { name: 'Gabon', code: 'GA', dial: '241', cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Mouila', 'Lambaréné', 'Tchibanga', 'Koulamoutou', 'Makokou'] },
  { name: 'Gambia', code: 'GM', dial: '220', cities: ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni', 'Lamin', 'Sukuta', 'Gunjur', 'Basse Santa Su', 'Janjanbureh'] },
  { name: 'Greece', code: 'GR', dial: '30', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Ioannina', 'Chania', 'Chalcis', 'Agrinio'] },
  { name: 'Guatemala', code: 'GT', dial: '502', cities: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'San Juan Sacatepéquez', 'Escuintla', 'Cobán', 'Chimaltenango', 'Huehuetenango', 'Totonicapán'] },
  { name: 'Guinea', code: 'GN', dial: '224', cities: ['Conakry', 'Nzérékoré', 'Kindia', 'Labé', 'Guéckédou', 'Kankan', 'Mamou', 'Kissidougou', 'Siguiri', 'Coyah'] },
  { name: 'Guinea-Bissau', code: 'GW', dial: '245', cities: ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama', 'Cacheu', 'Bubaque', 'Catió', 'Farim', 'Mansôa'] },
  { name: 'Guyana', code: 'GY', dial: '592', cities: ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica', 'Skeldon', 'Rosignol', 'Mahdia', 'Lethem', 'Corriverton'] },
  { name: 'Haiti', code: 'HT', dial: '509', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Delmas', 'Pétionville', 'Gonaïves', 'Les Cayes', 'Jacmel', 'Saint-Marc', 'Carrefour', 'Pétion-Ville'] },
  { name: 'Honduras', code: 'HN', dial: '504', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Villanueva', 'Choluteca', 'Comayagua', 'Juticalpa', 'Danlí'] },
  { name: 'Hong Kong', code: 'HK', dial: '852', cities: ['Hong Kong', 'Kowloon', 'Tuen Mun', 'Yuen Long', 'Sha Tin', 'Tai Po', 'Fanling', 'Tseung Kwan O', 'Tsuen Wan', 'Sai Kung'] },
  { name: 'Hungary', code: 'HU', dial: '36', cities: ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely'] },
  { name: 'Iran', code: 'IR', dial: '98', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia'] },
  { name: 'Iraq', code: 'IQ', dial: '964', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Kirkuk', 'Najaf', 'Karbala', 'Nasiriyah', 'Amarah'] },
  { name: 'Israel', code: 'IL', dial: '972', cities: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beersheba', 'Bnei Brak', 'Holon'] },
  { name: 'Jordan', code: 'JO', dial: '962', cities: ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Aqaba', 'Madaba', 'Jerash', 'Mafraq', 'Karak', 'Tafilah'] },
  { name: 'Kazakhstan', code: 'KZ', dial: '7', cities: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe', 'Taraz', 'Oskemen', 'Semey', 'Atyrau', 'Kostanay'] },
  { name: 'Kuwait', code: 'KW', dial: '965', cities: ['Kuwait City', 'Salmiya', 'Hawalli', 'Farwaniya', 'Ahmadi', 'Jahra', 'Shuwaikh', 'Fintas', 'Mahboula', 'Mangaf'] },
  { name: 'Lebanon', code: 'LB', dial: '961', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh', 'Nabatieh', 'Zahle', 'Baalbek', 'Byblos', 'Aley'] },
  { name: 'Liberia', code: 'LR', dial: '231', cities: ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper', 'Voinjama', 'Zwedru', 'Sanniquellie', 'Buchanan', 'Tubmanburg'] },
  { name: 'Libya', code: 'LY', dial: '218', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Al Khums', 'Zawiya', 'Zliten', 'Ajdabiya', 'Derna', 'Sabha'] },
  { name: 'Madagascar', code: 'MG', dial: '261', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Ambovombe', 'Moramanga', 'Manakara'] },
  { name: 'Malawi', code: 'MW', dial: '265', cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Karonga', 'Kasungu', 'Mangochi', 'Salima', 'Liwonde', 'Balaka'] },
  { name: 'Mali', code: 'ML', dial: '223', cities: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Kayes', 'Ségou', 'Gao', 'Kati', 'Koulikoro', 'Timbuktu'] },
  { name: 'Mauritania', code: 'MR', dial: '222', cities: ['Nouakchott', 'Nouadhibou', 'Néma', 'Kaédi', 'Rosso', 'Zouerate', 'Kiffa', 'Atar', 'Sélibabi', 'Akjoujt'] },
  { name: 'Mauritius', code: 'MU', dial: '230', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes', 'Triolet', 'Goodlands', 'Centre de Flacq', 'Mahébourg', 'Saint Pierre'] },
  { name: 'Moldova', code: 'MD', dial: '373', cities: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița', 'Cahul', 'Ungheni', 'Soroca', 'Orhei', 'Dubăsari'] },
  { name: 'Morocco', code: 'MA', dial: '212', cities: ['Casablanca', 'Rabat', 'Fez', 'Marrakesh', 'Agadir', 'Tangier', 'Meknès', 'Oujda', 'Kenitra', 'Tetouan', 'Safi', 'El Jadida', 'Khouribga', 'Beni Mellal', 'Nador', 'Taza', 'Settat', 'Larache', 'Khénifra', 'Berrechid'] },
  { name: 'Myanmar', code: 'MM', dial: '95', cities: ['Rangoon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa', 'Sittwe', 'Meiktila', 'Myingyan'] },
  { name: 'Namibia', code: 'NA', dial: '264', cities: ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund', 'Oshakati', 'Rehoboth', 'Katima Mulilo', 'Grootfontein', 'Otjiwarongo', 'Okahandja'] },
  { name: 'Nicaragua', code: 'NI', dial: '505', cities: ['Managua', 'León', 'Masaya', 'Tipitapa', 'Chinandega', 'Matagalpa', 'Estelí', 'Granada', 'Jinotega', 'Ciudad Sandino'] },
  { name: 'Niger', code: 'NE', dial: '227', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Arlit', 'Tahoua', 'Dosso', 'Diffa', 'Tillabéri', 'Birni Konni'] },
  { name: 'Oman', code: 'OM', dial: '968', cities: ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar', 'As Suwayq', 'Ibri', 'Saham', 'Barka', 'Rustaq'] },
  { name: 'Panama', code: 'PA', dial: '507', cities: ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Arraiján', 'La Chorrera', 'Colón', 'Chitré', 'Santiago', 'Las Tablas'] },
  { name: 'Papua New Guinea', code: 'PG', dial: '675', cities: ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Popondetta', 'Madang', 'Kokopo', 'Kimbe', 'Goroka', 'Wewak'] },
  { name: 'Paraguay', code: 'PY', dial: '595', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá', 'Lambaré', 'Fernando de la Mora', 'Limpio', 'Ñemby', 'Mariano Roque Alonso'] },
  { name: 'Peru', code: 'PE', dial: '51', cities: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Iquitos', 'Piura', 'Cusco', 'Chimbote', 'Huancayo', 'Tacna', 'Juliaca', 'Pucallpa', 'Ica', 'Sullana', 'Ayacucho', 'Cajamarca', 'Puno', 'Tarapoto', 'Tumbes', 'Huánuco'] },
  { name: 'Poland', code: 'PL', dial: '48', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'] },
  { name: 'Qatar', code: 'QA', dial: '974', cities: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah', 'Al Khor', 'Madinat ash Shamal', 'Dukhan', 'Mesaieed', 'Al Wukair', 'Lusail'] },
  { name: 'Romania', code: 'RO', dial: '40', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea'] },
  { name: 'Russia', code: 'RU', dial: '7', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Ufa', 'Rostov-on-Don'] },
  { name: 'Sierra Leone', code: 'SL', dial: '232', cities: ['Freetown', 'Koidu', 'Bo', 'Kenema', 'Makeni', 'Lunsar', 'Port Loko', 'Magburaka', 'Waterloo', 'Kabala'] },
  { name: 'Somalia', code: 'SO', dial: '252', cities: ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Marka', 'Bosaso', 'Baidoa', 'Beledweyne', 'Afgooye', 'Jawhar'] },
  { name: 'South Sudan', code: 'SS', dial: '211', cities: ['Juba', 'Wau', 'Malakal', 'Yei', 'Bor', 'Torit', 'Aweil', 'Yambio', 'Rumbek', 'Bentiu'] },
  { name: 'Sri Lanka', code: 'LK', dial: '94', cities: ['Colombo', 'Dehiwala', 'Moratuwa', 'Jaffna', 'Negombo', 'Kandy', 'Kalmunai', 'Trincomalee', 'Galle', 'Ratnapura'] },
  { name: 'Sudan', code: 'SD', dial: '249', cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'Obeid', 'Kosti', 'Wad Medani', 'El Fasher', 'Atbara', 'Gedaref'] },
  { name: 'Suriname', code: 'SR', dial: '597', cities: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Nieuw Amsterdam', 'Marienburg', 'Albina', 'Groningen', 'Apoera', 'Brokopondo'] },
  { name: 'Switzerland', code: 'CH', dial: '41', cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne'] },
  { name: 'Syria', code: 'SY', dial: '963', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hamah', 'Deir ez-Zor', 'Ar-Raqqah', 'Daraa', 'As-Suwayda', 'Tartus'] },
  { name: 'Taiwan', code: 'TW', dial: '886', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Keelung', 'Taoyuan', 'Chiayi', 'Changhua', 'Zhubei'] },
  { name: 'Thailand', code: 'TH', dial: '66', cities: ['Bangkok', 'Nonthaburi', 'Pak Kret', 'Hat Yai', 'Chiang Mai', 'Khon Kaen', 'Udon Thani', 'Nakhon Ratchasima', 'Ubon Ratchathani', 'Pattaya'] },
  { name: 'Togo', code: 'TG', dial: '228', cities: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Tsévié', 'Aného', 'Mango', 'Bassar', 'Sotouboua'] },
  { name: 'Tunisia', code: 'TN', dial: '216', cities: ['Tunis', 'Sfax', 'Sousse', 'Midoun', 'Kairouan', 'Bizerte', 'Gabès', 'Aryanah', 'Gafsa', 'Monastir'] },
  { name: 'Turkey', code: 'TR', dial: '90', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya', 'Mersin', 'Diyarbakır', 'Kayseri', 'Eskişehir', 'Samsun', 'Denizli', 'Sakarya', 'Trabzon', 'Malatya', 'Erzurum', 'Van', 'Manisa'] },
  { name: 'Ukraine', code: 'UA', dial: '380', cities: ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol'] },
  { name: 'Uruguay', code: 'UY', dial: '598', cities: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembó', 'Melo', 'Mercedes'] },
  { name: 'Uzbekistan', code: 'UZ', dial: '998', cities: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus', 'Fergana', 'Qarshi', 'Bukhara', 'Margilan', 'Chirchiq'] },
  { name: 'Venezuela', code: 'VE', dial: '58', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Maturín', 'Barcelona', 'Ciudad Guayana', 'San Cristóbal', 'Mérida'] },
  { name: 'Vietnam', code: 'VN', dial: '84', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho', 'Bien Hoa', 'Nha Trang', 'Hue', 'Buon Ma Thuot', 'Vinh'] },
  { name: 'Yemen', code: 'YE', dial: '967', cities: ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb', 'Dhamar', 'Al Mukalla', 'Amran', 'Sayyan', 'Zabid'] },
]
