import { NextRequest, NextResponse } from 'next/server'

// Full global currency map by country code
const CURRENCY_MAP: Record<string, { code: string; symbol: string; name: string; rate: number }> = {
  // Africa
  NG: { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', rate: 1650 },
  GH: { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', rate: 15.5 },
  KE: { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', rate: 129 },
  ZA: { code: 'ZAR', symbol: 'R', name: 'South African Rand', rate: 18.5 },
  ET: { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', rate: 56 },
  TZ: { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', rate: 2530 },
  UG: { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', rate: 3780 },
  EG: { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', rate: 48.5 },
  MA: { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', rate: 10.1 },
  DZ: { code: 'DZD', symbol: 'DA', name: 'Algerian Dinar', rate: 135 },
  TN: { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', rate: 3.1 },
  SN: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  CI: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  ML: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  BF: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  NE: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  TG: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  BJ: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  GW: { code: 'XOF', symbol: 'CFA', name: 'West African Franc', rate: 615 },
  CM: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  TD: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  CF: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  CG: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  GA: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  GQ: { code: 'XAF', symbol: 'FCFA', name: 'Central African Franc', rate: 615 },
  RW: { code: 'RWF', symbol: 'Fr', name: 'Rwandan Franc', rate: 1300 },
  BI: { code: 'BIF', symbol: 'Fr', name: 'Burundian Franc', rate: 2880 },
  ZM: { code: 'ZMW', symbol: 'K', name: 'Zambian Kwacha', rate: 26.5 },
  ZW: { code: 'USD', symbol: '$', name: 'US Dollar', rate: 1 },
  MZ: { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', rate: 63.5 },
  MG: { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', rate: 4500 },
  MU: { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', rate: 45.5 },
  AO: { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', rate: 850 },
  NA: { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', rate: 18.5 },
  BW: { code: 'BWP', symbol: 'P', name: 'Botswana Pula', rate: 13.6 },
  SD: { code: 'SDG', symbol: '£', name: 'Sudanese Pound', rate: 600 },
  SO: { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', rate: 571 },
  LY: { code: 'LYD', symbol: 'LD', name: 'Libyan Dinar', rate: 4.85 },
  // Europe
  GB: { code: 'GBP', symbol: '£', name: 'British Pound', rate: 0.79 },
  IE: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  FR: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  DE: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  ES: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  IT: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  PT: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  NL: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  BE: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  AT: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  FI: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  GR: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  LU: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  SK: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  SI: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  EE: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  LV: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  LT: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  MT: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  CY: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  HR: { code: 'EUR', symbol: '€', name: 'Euro', rate: 0.92 },
  CH: { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', rate: 0.90 },
  SE: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', rate: 10.5 },
  NO: { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', rate: 10.6 },
  DK: { code: 'DKK', symbol: 'kr', name: 'Danish Krone', rate: 6.9 },
  PL: { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', rate: 4.0 },
  CZ: { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', rate: 23.5 },
  HU: { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', rate: 364 },
  RO: { code: 'RON', symbol: 'lei', name: 'Romanian Leu', rate: 4.6 },
  BG: { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', rate: 1.80 },
  RS: { code: 'RSD', symbol: 'din', name: 'Serbian Dinar', rate: 108 },
  UA: { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', rate: 39.5 },
  TR: { code: 'TRY', symbol: '₺', name: 'Turkish Lira', rate: 32.5 },
  RU: { code: 'RUB', symbol: '₽', name: 'Russian Ruble', rate: 91 },
  // Americas
  US: { code: 'USD', symbol: '$', name: 'US Dollar', rate: 1 },
  CA: { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', rate: 1.36 },
  MX: { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', rate: 17.2 },
  BR: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', rate: 5.1 },
  AR: { code: 'ARS', symbol: '$', name: 'Argentine Peso', rate: 870 },
  CL: { code: 'CLP', symbol: '$', name: 'Chilean Peso', rate: 945 },
  CO: { code: 'COP', symbol: '$', name: 'Colombian Peso', rate: 3950 },
  PE: { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', rate: 3.7 },
  VE: { code: 'USD', symbol: '$', name: 'US Dollar', rate: 1 },
  EC: { code: 'USD', symbol: '$', name: 'US Dollar', rate: 1 },
  GT: { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', rate: 7.8 },
  JM: { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', rate: 157 },
  TT: { code: 'TTD', symbol: 'TT$', name: 'Trinidad Dollar', rate: 6.8 },
  // Asia & Pacific
  IN: { code: 'INR', symbol: '₹', name: 'Indian Rupee', rate: 83.5 },
  PK: { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', rate: 278 },
  BD: { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', rate: 110 },
  LK: { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', rate: 305 },
  NP: { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', rate: 133 },
  MM: { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', rate: 2100 },
  TH: { code: 'THB', symbol: '฿', name: 'Thai Baht', rate: 35.5 },
  VN: { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', rate: 24500 },
  ID: { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', rate: 15800 },
  PH: { code: 'PHP', symbol: '₱', name: 'Philippine Peso', rate: 56.5 },
  MY: { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', rate: 4.7 },
  SG: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', rate: 1.34 },
  CN: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', rate: 7.25 },
  JP: { code: 'JPY', symbol: '¥', name: 'Japanese Yen', rate: 149 },
  KR: { code: 'KRW', symbol: '₩', name: 'South Korean Won', rate: 1330 },
  HK: { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', rate: 7.82 },
  TW: { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar', rate: 31.5 },
  AU: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', rate: 1.53 },
  NZ: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', rate: 1.63 },
  AE: { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', rate: 3.67 },
  SA: { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', rate: 3.75 },
  QA: { code: 'QAR', symbol: 'QR', name: 'Qatari Riyal', rate: 3.64 },
  KW: { code: 'KWD', symbol: 'KD', name: 'Kuwaiti Dinar', rate: 0.31 },
  BH: { code: 'BHD', symbol: 'BD', name: 'Bahraini Dinar', rate: 0.38 },
  OM: { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', rate: 0.385 },
  IQ: { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', rate: 1310 },
  IR: { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', rate: 42000 },
  IL: { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', rate: 3.7 },
  JO: { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar', rate: 0.71 },
  LB: { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', rate: 89500 },
  KZ: { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', rate: 450 },
  UZ: { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som', rate: 12400 },
}

export async function GET(req: NextRequest) {
  const country = req.headers.get('x-vercel-ip-country') ||
                  req.headers.get('cf-ipcountry') || 'US'
  const currency = CURRENCY_MAP[country] || CURRENCY_MAP['US']
  return NextResponse.json({ country, currency })
}
